### PR TITLE
#157746823 Build out new request page

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Creates requests page where users make new requests.

#### Description of Task to be completed?
- Create a make new request page and add a  navbar
- Structure a request form and add necessary fields to the form
- Add footer to the page

#### How should this be manually tested?
1. Clone the branch into your local machine as follows
```
git clone -b ft-new-request-page-157746823 git@github.com:DennisWanjiru/maintenance-tracker.git 

cd maintenance-tracker/ui/pages

```
2. Open `new-request.html` with a browser

#### Any background context you want to provide?
Inspired by google forms.

#### What are the relevant pivotal tracker stories?
[#157746823](https://www.pivotaltracker.com/story/show/157746823)

#### Screenshots (if appropriate)
request-form

#### Questions:
- Does the request form contain all the necessary fields to enable users successfully make a new request?

### CODE REVIEW

**Comment by gitaumoses4** [comment]
Your design intrigues me. Awesome work. Love the material design. :+1:

**Comment by asamisellah** [comment]
Really clean and simple form. Maybe you can categories for the services

**Comment by joelmachango** [comment]
Good job on the material design @DennisWanjiru

**Comment by denniswanjiru** [comment]
@asamisellah noted. Thanks for the review @asamisellah @gitaumoses4 @joelmachango

**Comment by mmosoroohh** [comment]
Awesome work....

**Pull request merged**
