### PR TITLE
#157762624 Make the app responsive

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Making the client-side mobile friendly

#### Description of Task to be completed?
- Make  signup page responsive
- Make  signin page responsive
- Make landing page responsive
- Make  requests page responsive
- Make new-request page responsive
- Make header responsive
- Make footer responsive
- Create a mobile sidebar

#### How should this be manually tested?
1. Clone the branch into your local machine as follows
```
git clone -b ft-responsive-layout-157762624 git@github.com:DennisWanjiru/maintenance-tracker.git 

cd maintenance-tracker/ui/dashboard/

```
2. Open `request-details.html` with a browser
3. `ctrl+shift+j` and view in mobile simulation mode

#### Any background context you want to provide?
Media query `breakpoint == 600px`

#### What are the relevant pivotal tracker stories?
[#157762624](https://www.pivotaltracker.com/story/show/157762624)

#### Screenshots (if appropriate)
mobile

### Questions?
Is the page mobile friendly?

### CODE REVIEW

**Comment by asamisellah** [comment]
Good design for mobile for the pages I've viewed

**Comment by asamisellah** [comment]
Responsiveness has been achieved

**Comment by denniswanjiru** [comment]
Thanks for the review @asamisellah

**Comment by Slinjez** [comment]
The sidebar looks cool

**Comment by joelmachango** [comment]
Amazing work. Your design is stunning! @DennisWanjiru

**Comment by gitaumoses4** [comment]
This is awesome. Love your design.

**Comment by denniswanjiru** [comment]
Thanks guys

**Pull request merged**
