### PR TITLE
#157746721 Build user requests page

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Creates requests page where users can view all their requests

#### Description of Task to be completed?
- Link the  Request url on landing-page to the all-request page 
- Add a navbar
- Design a Request card
- Design Layout for the Requests page
- Add a footer
- Create filters
- Create search bar to search a request
- Create order by button

#### How should this be manually tested?
1. Clone the branch into your local machine as follows
```
git clone -b ft-user-requests-page-157746721 git@github.com:DennisWanjiru/maintenance-tracker.git 

cd maintenance-tracker/ui/pages

```
2. Open `request.html` with a browser

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#157746721](https://www.pivotaltracker.com/story/show/157746721)

#### Screenshots (if appropriate)
requests

#### Questions:
- Does the request card hold all the necessary overview information?

### CODE REVIEW

**Comment by zakhusayn** [comment]
Great work!. a descriptive card and well documented PR. 
i just hope it's responsive

**Comment by joelmachango** [comment]
@DennisWanjiru Very nice UI. The PR is well structured.

**Comment by denniswanjiru** [comment]
@blac-siren it's not responsive at theoment but I will work on it.  Thanks @joelmachango

**Comment by Slinjez** [comment]
dope UI its looking good, the pr is also well structured,  so good job

**Pull request merged**
