### PR TITLE
157746921 Build out landing page

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Creates the landing page for the project

#### Description of Task to be completed?
- Adds a header with a navbar and a call-to-action button
- Adds a `how it works` section
- Adds a footer for to the landing page

#### How should this be manually tested?
1. Clone the repo into your local machine as follows
```
git clone git@github.com:DennisWanjiru/maintenance-tracker.git

cd maintenance-tracker/ui/

```
2. Open `index.html` with a browser

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#157746921](https://www.pivotaltracker.com/story/show/157746921)

#### Screenshots (if appropriate)
**Landing Page Header**

landing-header

**How it works**

how-it-works

**Footer**

rsz_footer

#### Questions:
- Does the landing page get the users attention?

### CODE REVIEW

**Comment by Melvin1Atieno** [comment]
It sure does!!! Got mine at least

**Comment by lawrenceChege** [comment]
The UI is great! well done
it definitely gets the user attention

**Comment by dessHub** [comment]
Well, design is spectacular . Github best practices are all observed . Good work

**Comment by johnmusiu** [comment]
The UI is wow, caught my eye
PR looks ok too

**Comment by denniswanjiru** [comment]
Thanks for the reviews guys. Highly appreciated

**Comment by joelmachango** [comment]
@DennisWanjiru Well structured PR. Beautiful design!

**Comment by janetnim** [comment]
True your UI is amazing

**Comment by Slinjez** [comment]
lovely design

**Pull request merged**
