### PR TITLE
#157778725  Update README 

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
This PR will update the README file with useful information

#### Description of Task to be completed?
- Add a licence badge 
- Add apps' landing page image
- Add guidance on how to use the app
- Add guidance on how to install the project
- Add a list of technologies and languages used
- Add guidance on how to contribute to this project

#### How should this be manually tested?
1. Clone repository 
``` 
git clone git@github.com:DennisWanjiru/maintenance-tracker.git

cd maintenance-tracker/

git checkout ch-update-readme-157778725

```
3. Open `README.md` file in  [visual studio code](https://code.visualstudio.com/)
2. Press `ctrl+shift+v` to preview the readme

#### Any background context you want to provide?
To achieve this README I used the following tutorials and tools 
- [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)
- [Readme Badges](https://shields.io/)
- [Github emojis](https://gist.github.com/rxaviers/7360908)
- [Add image to readme](https://www.tilcode.com/add-a-screenshot-to-your-github-repo-readme-md/)

#### What are the relevant pivotal tracker stories?
[#157778725](https://www.pivotaltracker.com/story/show/157778725)
[#157832520](https://www.pivotaltracker.com/story/show/157832520)
[#157836999](https://www.pivotaltracker.com/story/show/157836999)

### CODE REVIEW

**Comment by asamisellah** [comment]
Awesome README. Very detailed

**Comment by mmosoroohh** [comment]
Amazing ReadMe bro...
Very detailed and informative.

**Comment by Melvin1Atieno** [comment]
Getting an error on the link to open the ReadMe file. Check that out

**Comment by dessHub** [comment]
Good work.. Check  **Open README** link , it has an error.

**Pull request merged**
