### PR TITLE
#157746461 Build out Request detail page

### PR DESCRIPTION
**Pull request by denniswanjiru**
#### What does this PR do?
Creates a page where the admin can see details of a requests.

#### Description of Task to be completed?
- Create a card to hold details of a request
- Create a call to action buttons where admin can reject aor approve a request
- Create a button where an admin can resolve a done request

#### How should this be manually tested?
1. Clone the branch into your local machine as follows
```
git clone -b ft-request-details-page-157746461 git@github.com:DennisWanjiru/maintenance-tracker.git 

cd maintenance-tracker/ui/dashboard/

```
2. Open `request-details.html` with a browser

#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[#157746461](https://www.pivotaltracker.com/story/show/157746461)
[#157746537](https://www.pivotaltracker.com/story/show/157746537)
[#157746570](https://www.pivotaltracker.com/story/show/157746570)

#### Screenshots (if appropriate)
request-details

### CODE REVIEW

**Comment by gtsofa** [comment]
Nice designs!!!

**Comment by asamisellah** [comment]
Once again, your UI is very simple and clean...awesome. Good PR

**Comment by lawrenceChege** [comment]
good work. Nice UI design

**Comment by asamisellah** [comment]
Very clean design. Detailed PR

**Pull request merged**
