### PR TITLE
#157746105 Design user signup page

### PR DESCRIPTION
**Pull request by denniswanjiru**
**What does this PR do?**
This PR contains a user signup page design

**Description of the tasks to be completed**
Contains the following input fields
- User Fullname
- User Email address
- Password
- Password Confirmation

**How should this be manually tested?**
1. Clone the repo into your local machine as follows
```
git clone git@github.com:DennisWanjiru/maintenance-tracker.git

cd maintenance-tracker/ui/auth/signup.html

```
2. The signup.html on a browser

**Any background context you want to provide?**
The page is designed using html5 and css3

**What are the relevant pivotal tracker stories**
#157746105

**Screenshots (if appropriate)**

signup

### CODE REVIEW

**Comment by asamisellah** [comment]
Your PR is brief and to the point. No conflicts. I like your sign up page design.

**Comment by RuthNjeri** [comment]
Great and detailed design.

**Comment by denniswanjiru** [comment]
Thanks for the feedback much appreciated

**Comment by dalaineme** [comment]
:tada: :tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Pull request merged**
