### PR TITLE
#157746105 Built UI for user registration

### PR DESCRIPTION
**Pull request by denniswanjiru**
**What does this PR do?**
This PR contains a user signup page design

**Description of the tasks to be completed**
Contains the following input fields
- User Fullname
- User Email address
- Password
- Password Confirmation

**How should this be manually tested?**
1. Clone the repo into your local machine as follows
```
git clone git@github.com:DennisWanjiru/maintenance-tracker.git

cd maintenance-tracker/ui/auth

```
2. Open the signup.html on a browser

**Any background context you want to provide?**
The page is designed using html5 and css3

**What are the relevant pivotal tracker stories**
[#157746105](https://www.pivotaltracker.com/story/show/157746105)

**Screenshots (if appropriate)**

signup

### CODE REVIEW

**Comment by asamisellah** [comment]
Good PR, no conflicts, good design

**Comment by johnmusiu** [comment]
When you cd you can't have a file at the end, it ought to be:
```cd maintenance-tracker/ui/auth/```
Well detailed PR
Cool UI. I'd like to see what happens when you are typing into a field though

**Comment by denniswanjiru** [comment]
@johnmusiu thank you I have edited the folder navigation. Thanks alot for the review @asamisellah  and @johnmusiu

**Comment by Slinjez** [comment]
This is elegant design

**Comment by Eyansky** [comment]
Screen shot looks good, you closed the pull request though

**Pull request merged**
